const outfits = [
  { id: 'none', name: 'Original', category: 'Básicos', style: 'none', primary: '#d4d7d4', secondary: '#8c948f', accent: '#f2f2f5', icon: '•' },
  { id: 'scarf', name: 'Cachecol', category: 'Básicos', style: 'scarf', primary: '#a86bc2', secondary: '#713f87', accent: '#f1bfdc', icon: '❄' },
  { id: 'cape', name: 'Capa heroica', category: 'Cultura pop', style: 'cape', primary: '#a52e42', secondary: '#641b32', accent: '#f3c94e', icon: '✦' },
  { id: 'cosmic-hero', name: 'Batman', category: 'Cultura pop', style: 'batman', primary: '#343a45', secondary: '#11151c', accent: '#e4c54e', icon: '🦇' },
  { id: 'web-hero', name: 'Herói aracnídeo', category: 'Cultura pop', style: 'spider', primary: '#c52d39', secondary: '#711d30', accent: '#2453a8', icon: '✧' },
  { id: 'wizard', name: 'Mago da escola', category: 'Filmes e animação', style: 'robe', primary: '#34274f', secondary: '#1c1930', accent: '#c69b45', icon: '✦' },
  { id: 'space-knight', name: 'Darth Vader', category: 'Filmes e animação', style: 'vader', primary: '#292b30', secondary: '#090a0c', accent: '#d5d8dc', icon: '◉' },
  { id: 'red-plumber', name: 'Mario', category: 'Filmes e animação', style: 'mario', primary: '#c3312d', secondary: '#7b2024', accent: '#315caa', icon: 'M' },
  { id: 'mickey-mouse', name: 'Mickey Mouse', category: 'Filmes e animação', style: 'mouse', primary: '#25252b', secondary: '#15151a', accent: '#d8443e', icon: '●' },
  { id: 'indiana-jones', name: 'Indiana Jones', category: 'Filmes e animação', style: 'explorer', primary: '#815333', secondary: '#4d3025', accent: '#d0a052', icon: '◆' },
  { id: 'james-bond', name: 'James Bond (007)', category: 'Filmes e animação', style: 'bond', primary: '#202b3b', secondary: '#111722', accent: '#e7e7e4', icon: '007' },
  { id: 'joker', name: 'Coringa', category: 'Filmes e animação', style: 'joker', primary: '#542c70', secondary: '#2d1b41', accent: '#4da45e', icon: '♠' },
  { id: 'yellow-sidekick', name: 'Amarelinho de jardineira', category: 'Filmes e animação', style: 'overalls-goggles', primary: '#e9b92f', secondary: '#a8781b', accent: '#345fa4', icon: '◉' },
  { id: 'orange-martial', name: 'Guerreiro laranja', category: 'Filmes e animação', style: 'martial', primary: '#e8782f', secondary: '#a84428', accent: '#253d79', icon: '✦' },
  { id: 'ogre-adventurer', name: 'Aventureiro do pântano', category: 'Filmes e animação', style: 'ogre', primary: '#6c8740', secondary: '#374d2c', accent: '#a67c4b', icon: '♧' },
  { id: 'pirate', name: 'Capitão pirata', category: 'Filmes e animação', style: 'pirate', primary: '#47334b', secondary: '#241e2d', accent: '#bc3740', icon: '☠' },
  { id: 'royal', name: 'Realeza encantada', category: 'Filmes e animação', style: 'royal', primary: '#bd588d', secondary: '#78355d', accent: '#edc454', icon: '♛' },
  { id: 'pop-star', name: 'Madonna', category: 'Música', style: 'madonna', primary: '#e9d9ce', secondary: '#c4a18f', accent: '#df8eae', icon: '♫' },
  { id: 'rock-star', name: 'Freddie Mercury', category: 'Música', style: 'freddie', primary: '#e9c33e', secondary: '#9c6d1f', accent: '#f3eee1', icon: '♫' },
  { id: 'king-of-pop', name: 'Michael Jackson', category: 'Música', style: 'mj', primary: '#24252a', secondary: '#111216', accent: '#e9c24d', icon: '♪' },
  { id: 'elvis-presley', name: 'Elvis Presley', category: 'Música', style: 'elvis', primary: '#f0eee5', secondary: '#b8b8b4', accent: '#d4b74f', icon: '♫' },
  { id: 'country-star', name: 'Cantor country', category: 'Música', style: 'country', primary: '#805137', secondary: '#4c3028', accent: '#d99a43', icon: '♬' },
  { id: 'rap-star', name: 'Rapper urbano', category: 'Música', style: 'rap', primary: '#344c76', secondary: '#1f2d48', accent: '#e3b846', icon: '♫' },
  { id: 'president-brazil', name: 'Lula da Silva', category: 'Presidentes', style: 'president-lula', primary: '#263a45', secondary: '#17232b', accent: '#cf3f48', icon: '★' },
  { id: 'president-america', name: 'Barack Obama', category: 'Presidentes', style: 'president-obama', primary: '#203861', secondary: '#152342', accent: '#5e8ec6', icon: '★' },
  { id: 'president-classic', name: 'Donald Trump', category: 'Presidentes', style: 'president-trump', primary: '#353942', secondary: '#1d2027', accent: '#c3333a', icon: '★' },
  { id: 'doctor', name: 'Médico', category: 'Profissões', style: 'labcoat', primary: '#e5e8e8', secondary: '#aab6ba', accent: '#54a8a0', icon: '✚' },
  { id: 'surgeon', name: 'Cirurgião', category: 'Profissões', style: 'scrubs', primary: '#398e8b', secondary: '#205a62', accent: '#d8e5e3', icon: '✚' },
  { id: 'scientist', name: 'Cientista', category: 'Profissões', style: 'labcoat', primary: '#dce4e3', secondary: '#879b9c', accent: '#8766a8', icon: '⚗' },
  { id: 'astronaut', name: 'Astronauta', category: 'Profissões', style: 'astronaut', primary: '#dce0e2', secondary: '#818c9b', accent: '#4379bb', icon: '✧' },
  { id: 'chef', name: 'Chef de cozinha', category: 'Profissões', style: 'chef', primary: '#ece9df', secondary: '#b7b1a4', accent: '#c7463d', icon: '♨' },
  { id: 'firefighter', name: 'Bombeiro', category: 'Profissões', style: 'firefighter', primary: '#b94131', secondary: '#722721', accent: '#f1c74d', icon: '✦' },
  { id: 'detective', name: 'Detetive', category: 'Profissões', style: 'detective', primary: '#745f47', secondary: '#403832', accent: '#d4c19a', icon: '⌕' },
  { id: 'programmer', name: 'Programador', category: 'Profissões', style: 'hoodie', primary: '#394c81', secondary: '#202b50', accent: '#65cfbb', icon: '{ }' },
  { id: 'pilot', name: 'Piloto', category: 'Profissões', style: 'pilot', primary: '#263e66', secondary: '#172741', accent: '#e4ba53', icon: '✈' },
  { id: 'builder', name: 'Construtor', category: 'Profissões', style: 'builder', primary: '#e47e36', secondary: '#a44c2c', accent: '#efcf50', icon: '⚒' },
];

if (typeof module !== 'undefined' && module.exports) module.exports = outfits;
else window.PipOutfitCatalog = outfits;
